name: build and push docker
on: [workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v4
        with:
          ref: 'refs/tags/v.0.1.0'
      - name: Show files
        run: ls -la
